### ISSUE TITLE
can't get out of gallery on 4s

### ISSUE THREAD

**Issue by adam-zethraeus** [adam-zethraeus/Lomo41#11]
bug report by the venerable @alexmuller

the custom toolbar seems to be hardcoded to be at an iphone-5-screen-size distance from the top.

**Comment by adam-zethraeus** [comment]
fixed: https://github.com/zethraeus/Lomo41/commit/80af0c0506498a07da5336ae35dee5de2efd3b63

**Comment by alexmuller** [comment]
:lollipop:
